server:
  port: 9000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/cloud_auth?allowMultiQueries=true&autoReconnect=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
  application:
    name: cloud-auth
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  redis:
    host: localhost
    port: 6379
    database: 0
common:
  system-user-id: 122333